name: Trivy Image Scan

on:
  workflow_run:
    workflows: ["Product Catalog CI"]
    types:
      - completed

permissions:
  contents: read
  security-events: write

jobs:
  trivy-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: 'docker.io/${{ secrets.DOCKERHUB_USERNAME }}/product-catalog:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'